### ISSUE TITLE
Why use External IPs to connect to nodes when syncing profiles?

### ISSUE THREAD

**Issue by Hunter1016** [sysdiglabs/kube-apparmor-manager#4]
In many scenarios, node does not has an External IP assigned, syncing get failed. I wonder why use External IPs to connect to nodes when syncing profiles?
https://github.com/sysdiglabs/kube-apparmor-manager/blob/6b8ff077ff4cfd4e88ae0b6b79a3be46be308e86/aa/service.go#L144

**Comment by B3ns44d** [comment]
same issue!

**Comment by Kaizhe** [comment]
The #5 fixes the issue and a new release is published.
